language: php

php: 
  - 5.3
  - 5.4
  - 5.5

before_script:
  - composer install --prefer-source --no-interaction --dev
  - sudo apt-get remove -y imagemagick libmagickcore-dev libmagickwand-dev
  - sudo apt-get install -y libtiff-dev libjpeg-dev libdjvulibre-dev libwmf-dev pkg-config
  - sh -c "
              wget http://www.imagemagick.org/download/legacy/ImageMagick-6.8.5-10.tar.gz;
              tar xzf ImageMagick-6.8.5-10.tar.gz;
              cd ImageMagick-6.8.5-10;
              ./configure --prefix=/opt/imagemagick;
              make -j;
              sudo make install;
              export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:/opt/imagemagick/lib/pkgconfig;
              sudo ln -s /opt/imagemagick/include/ImageMagick-6 /opt/imagemagick/include/ImageMagick;
              cd ..;
              wget http://pecl.php.net/get/imagick-3.1.0RC2.tgz;
              tar -xzf imagick-3.1.0RC2.tgz;
              cd imagick-3.1.0RC2;
              phpize;
              ./configure --with-imagick=/opt/imagemagick;
              make -j;
              sudo make install;
              echo \"extension=imagick.so\" >> `php --ini | grep \"Loaded Configuration\" | sed -e \"s|.*:\s*||\"`;
              php --ri imagick;
            "
  - sh -c "
              sudo apt-get install -y graphicsmagick libgraphicsmagick1-dev;
              wget http://pecl.php.net/get/gmagick-1.1.0RC3.tgz;
              tar -xzf gmagick-1.1.0RC3.tgz;
              cd gmagick-1.1.0RC3;
              phpize;
              ./configure --with-gmagick=/usr/local;
              make -j;
              sudo make install;
              echo \"extension=gmagick.so\" >> `php --ini | grep \"Loaded Configuration\" | sed -e \"s|.*:\s*||\"`;
              php --ri gmagick;
            "

script: phpunit -c phpunit.xml --coverage-text

after_script:
  - php vendor/bin/coveralls -v
